global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "alertmanager:9093"

rule_files:
  - "rules.yml"

scrape_configs:
  - job_name: "kafka-exporter"
    static_configs:
      - targets:
        - "kafka-exporter:9308"
    scrape_interval: 10s

  - job_name: "prometheus"
    static_configs:
      - targets:
        - "localhost:9090"

  - job_name: "alertmanager"
    static_configs:
      - targets:
        - "alertmanager:9093"

  - job_name: 'nginx-exporter'
    static_configs:
      - targets: 
        - "nginx-exporter:9113"
    scrape_interval: 10s
  - job_name: 'node'
    static_configs:
      - targets:
        - "IP_OF_NODE_EXPORTER_CONTAINER:9100"
  - job_name: 'Loki'
    static_configs:
      - targets:
        - "loki:3100"
  - job_name: 'fluentbit'
    metrics_path: '/api/v1/metrics/prometheus'
    static_configs:
      - targets:
        - "fluentbit:2020"
